name: Display Secret Value

on: [push]

jobs:
  display-secret:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print secret value
        run: echo "Secret TEST value is ${{ secrets.TEST }}"

