name: Display Secret Value

on: [push]

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    environment: Next
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.3
        with:
          debug: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd temp/lcc-mytsg
            docker-compose down && \
            docker rm -f $(docker ps -a -q)
            sudo rm -rf temp
            mkdir -p temp && \
            cd temp && \
            git clone git@github.com:tsgdigitalservices/lcc-mytsg.git && \
            cd lcc-mytsg && \
            sudo docker-compose build && \
            sudo docker-compose up -d &&
